<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>firstLineMatch</key>
	<string>.*&lt;:.*:=.*</string>
	<key>foldingStartMarker</key>
	<string>&lt;:</string>
	<key>foldingStopMarker</key>
	<string>:&gt;</string>
	<key>name</key>
	<string>FileMaker Hash</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(/*&lt;/*:)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.fmahash</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.fmahash</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(/*:?/*=)</string>
			<key>name</key>
			<string>meta.tag.filemaker.fmhash</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(/*&lt;/*:)|(/*:/*&gt;)|(/*:/*=)</string>
					<key>name</key>
					<string>punctuation.definition.tag.fmahash</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[-_a-zA-Z0-9:]+</string>
					<key>name</key>
					<string>entity.name.tag.localname.fmhash</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.fmahash</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(/*:/*&gt;)</string>
			<key>name</key>
			<string>mata.tag.filemaker.fmhash</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.filemaker.hash</string>
	<key>uuid</key>
	<string>E06766B0-3F1B-494C-886E-6CFFEF39FFF0</string>
</dict>
</plist>
