<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>firstLineMatch</key>
	<string>.*&lt;:.*?:=</string>
	<key>foldingStartMarker</key>
	<string>^\s*&lt;:(?!.+?:&gt;)</string>
	<key>foldingStopMarker</key>
	<string>^((?&lt;!&lt;:).)*?:&gt;(?!.*&lt;:.*)</string>
	<key>keyEquivalent</key>
	<string>^~F</string>
	<key>name</key>
	<string>FileMaker Hash</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(/*)&lt;\1:</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>entity.name.tag.localname.xml</string>
			<key>end</key>
			<string>\1:\1=</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(/*&lt;/*:)|(/*:/*&gt;)|(/*:/*=)</string>
					<key>name</key>
					<string>punctuation.definition.tag</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(/*:/*&gt;)</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.filemaker.hash</string>
	<key>uuid</key>
	<string>E06766B0-3F1B-494C-886E-6CFFEF39FFF0</string>
</dict>
</plist>
